feat: `with-secrets`: now mounts & cds into a tmp dir

diff --git a/scripts/with-secrets b/scripts/with-secrets
--- a/scripts/with-secrets
+++ b/scripts/with-secrets
@@ -1,36 +1,33 @@
 #!/bin/sh
 
-# # The first attempt
-# set -u
-#
-# secret="${1}"
-# name="${secret##*/}"
-# name="${name%%.*}"
-# extracted="/tmp/${name}"
-#
-# [ -z "${WITH_SECRETS_UNSHARED-}" ] && export WITH_SECRETS_UNSHARED=1 && exec unshare -m "${0}" "${@}"
-#
-# mount -t tmpfs tmpfs /tmp
-#
-# mkdir "${extracted}"
-# gpg --quiet --decrypt "${secret}" | tar -xf - -C "${extracted}"
-#
-# shift
-#
-# "${@}"
-
 set -u
+set -x
 
 : "${SUDO_UID:=$(id -u)}"
 : "${SUDO_GID:=$(id -g)}"
 
 path="${1}"
+initial_pwd="$(pwd)"
 shift
-printf '"%s"\n' "${@}"
 
-trap "cryfs-unmount --immediate '${path}' >/dev/null && chown -R ${SUDO_UID}:${SUDO_GID} '${path}-crypted'" EXIT HUP INT QUIT TERM
+mount="$(mktemp -d)"
+clean=false
+cleanup() {
+  ! [ "${clean}" = true ] && return
+  clean=true
+  cd "${initial_pwd}"
+  # NOTE: can fail pretty much only if something else cd'ed into the folder!
+  #       spooky!
+  for _ in $(seq 3) :; do
+    cryfs-unmount --immediate "${mount}" && break
+    sleep 3;
+  done
+  chown -R "${SUDO_UID}:${SUDO_GID}" "${path}" >&2
+  rmdir "${mount}"
+}
+trap "cleanup" EXIT HUP INT QUIT TERM
 
-cryfs "${path}-crypted" "${path}" >/dev/null || exit 1
+cryfs "${path}" "${mount}" >/dev/null || exit 1
+cd "${mount}" || exit 1
 
 "${@}"
-
